@startuml diagramme_de_cas_d'utilisation
left to right direction
actor Utilisateur
actor Administrateur

rectangle "FindMyTech" {
  
  (Rechercher un produit) as UC1
  (Filtrer par catégorie et budget) as UC3
  (Consulter la fiche technique) as UC4
  (Comparer des produits) as UC2
  (Ajouter un produit au panier) as UC8
  (Passer une commande) as UC9
  (Effectuer un paiement) as UC10

  (Ajouter un produit à la base de données) as UC5
  (Modifier/Supprimer un produit) as UC6
  (Gérer les utilisateurs) as UC7
  (Gérer les commandes) as UC11
  
  Utilisateur --> UC1
  Utilisateur --> UC2
  Utilisateur --> UC3
  Utilisateur --> UC4
  Utilisateur --> UC8
  Utilisateur --> UC9
  Utilisateur --> UC10
  
  Administrateur --> UC5
  Administrateur --> UC6
  Administrateur --> UC7
  Administrateur --> UC11
}

@enduml
